spring.application.name=Game_API

spring.datasource.url=jdbc:postgresql://localhost:5432/gamedb
spring.datasource.username=root
spring.datasource.password=root

api.security.token.secret = ${JWT_SECRET:my-secret-key}